security:
  authentication:
    # Multi-factor authentication configuration
    mfa:
      enabled: true
      providers:
        - type: totp
        - type: email_verification
        - type: backup_codes
    
    # Password policy
    password_policy:
      min_length: 12
      require_complexity: true
      max_attempts: 5
      lockout_duration: 15  # minutes
      
    # Session management
    session:
      max_concurrent_sessions: 3
      session_timeout: 60  # minutes
      
  authorization:
    # Role-based access control
    roles:
      admin:
        permissions:
          - full_platform_access
          - world_generation
          - mod_generation
          - content_management
      
      developer:
        permissions:
          - mod_generation
          - world_generation
          - limited_content_access
      
      user:
        permissions:
          - basic_world_generation
          - content_search
          - limited_mod_generation
    
  encryption:
    # Encryption settings
    tls:
      min_version: TLS1.3
      cipher_suites:
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
    
    data_encryption:
      at_rest:
        algorithm: AES-256-GCM
        key_rotation_interval: 90  # days
      
      in_transit:
        algorithm: ChaCha20-Poly1305
        min_key_size: 256
    
  mod_security:
    # Mod and content validation
    validation:
      scan_for_malware: true
      check_dependencies: true
      verify_source: true
      sandbox_testing: true
    
    blocklist:
      - known_malicious_mods
      - outdated_incompatible_mods
    
  network_security:
    # Network protection
    firewall:
      enabled: true
      default_policy: deny
      allowed_ports:
        - 8000  # Core platform
        - 5000  # API
        - 3000  # Frontend
    
    ddos_protection:
      enabled: true
      rate_limit: 100  # requests per minute
      block_duration: 30  # minutes
    
  audit_logging:
    # Comprehensive logging
    enabled: true
    retention_period: 365  # days
    log_levels:
      - security_events
      - authentication_attempts
      - mod_generation
      - world_generation
      - content_search
    
    export_formats:
      - json
      - csv
      - parquet
    
  compliance:
    # Regulatory compliance
    gdpr:
      data_minimization: true
      right_to_erasure: true
      consent_management: true
    
    privacy:
      anonymize_telemetry: true
      opt_out_tracking: true

# Machine Learning Security
ml_security:
  model_protection:
    adversarial_defense:
      enabled: true
      detection_threshold: 0.95
    
    model_validation:
      check_bias: true
      performance_monitoring: true
      
  data_poisoning_prevention:
    training_data_validation: true
    model_drift_detection: true
