mlsp:
  version: 1.0.0
  platform_support:
    - archcraft
    - macos
    - windows
  
  security:
    default_password: ChaosVT
    encryption:
      tls_enabled: true
      min_tls_version: 1.3
  
  minecraft:
    supported_versions:
      - 1.16.5
      - 1.17.1
      - 1.18.2
      - 1.19.4
      - 1.20.1
    server_types:
      - spigot
      - paper
      - forge
      - fabric
      - bedrock
  
  modules:
    server_management:
      enabled: true
      auto_update: true
    
    monetization:
      enabled: true
      virtual_economy: true
    
    voice_modulation:
      enabled: true
      ml_frameworks:
        - tensorflow
        - pytorch
    
    vr_ar:
      enabled: true
      platforms:
        - steamvr
        - oculus
        - openxr
    
    ai:
      enabled: true
      npc_generation: true
      procedural_generation: true
    
    community:
      enabled: true
      forums: true
      real_time_chat: true
    
    content_creator:
      enabled: true
      tools:
        - blender
        - live2d
    
    security:
      firewall:
        archcraft: ufw
        macos: built-in
        windows: defender
      
      container_support:
        - docker
        - kubernetes

  dependencies:
    java:
      min_version: 17
    docker:
      min_version: 24.0.0
    nodejs:
      min_version: 16.0.0
    python:
      min_version: 3.9
