title: Minecraft Local Server Platform
description: Advanced AI-driven Minecraft server platform
theme: jekyll-theme-cayman
show_downloads: true
google_analytics: UA-XXXXXXXX-X

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social Media and Contact
github:
  repository_url: https://github.com/yourusername/MLSP
  owner_name: Your Name
  owner_email: your.email@example.com

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - tests/
